//!============>> Copyright (c) 2017-2023 Darkside Interactive, Ltd. All rights reserved. <<============//
//
//? Цель: цветовые коды HTML & HEX формата
//
//!=====================================================================================================//

#define format_black    0xFF
#define Default         "{FFFFFF}" //! ?????? ???? ?????? ???????????? ? ????????????? ??????? (??? ??????????? ???? ????? ? ????? hex)

#define format_white    0xFFFFFFFF
#define format_red      0xFF0000FF
#define format_orange   0xffde26AA  


#define COLOR_SEA 						(0x00808000)
#define COLOR_REL                       (0xff634700)
#define COLOR_GRAD1 					(0xB4B5B700)
#define COLOR_GRAD2 					(0xBFC0C200)
#define COLOR_GRAD3 					(0xCBCCCE00)
#define COLOR_GRAD4 					(0xD8D8D800)
#define COLOR_GRAD5 					(0xE3E3E300)
#define COLOR_GRAD6 					(0xF0F0F0FF)
#define COLOR_GREY 						(0xAFAFAFAA)
#define COLOR_GREEN 					(0x63BD4EFF)
#define COLOR_RED 						(0xF04245FF)
#define COLOR_LIGHTRED 					(0xFF6347AA)
#define COLOR_LIGHTBLUE 				(0x33CCFFAA)
#define COLOR_LIGHTGREEN 				(0x9ACD32AA)
#define COLOR_ORANGE                    (0xFF9900FF)
#define COLOR_DARKORANGE                (0xFF6600FF)
#define COLOR_YELLOW 					(0xead86aFF)
#define COLOR_YELLOW2 					(0xF5DEB3AA)
#define COLOR_WHITE 					(0xFFFFFFAA)
#define COLOR_FADE1 					(0xE6E6E6E6)
#define COLOR_FADE2 					(0xC8C8C8C8)
#define COLOR_TOMATO 					(0xFF6347AA)
#define COLOR_FADE3 					(0xAAAAAAAA)
#define COLOR_FADE4 					(0x8C8C8C8C)
#define COLOR_BLUE 						(0x3399FFFF)
#define COLOR_FADE5 					(0x6E6E6E6E)
#define COLOR_PURPLE 					(0xDD90FFAA)
#define COLOR_LIME						(0x66CC00AA)
#define COLOR_DBLUE 					(0x2641FEAA)
#define COLOR_ALLDEPT 					(0xFF8282AA)
#define COLOR_NEWS 						(0xFFA500AA)
#define COLOR_OOC 						(0xE0FFFFAA)
#define COLOR_ORANG 					(0xF3BB33FF)
#define TEAM_BLUE_COLOR 				(0x8D8DFF00)
#define COLOR_BLACK 					(0x000000AA)
#define COLOR_BOX   					(0x00000050)
#define COLOR_BBLUE 					(0x20A9FFAA)
#define COLOR_BORDER 					(0x00000AA)
#define COLOR_INDIGO 					(0x4B00B0AA)
#define COLOR_GRENNN  					(0x97B96CAA)
#define COLOR_SYSTEM 					(0xEFEFF7AA)
#define COLOR_GREN  					(0x97B96CAA)


// macro scm
#define error_color 0xF04245FF
#define log_color 0x8DB600FF
#define warning_color 0xCFB53BFF
#define info_color 0x8FC248FF

// macro (originally)

#define Err_color       "{F04245}"
#define Log_color       "{8DB600}"
#define Warn_color      "{CFB53B}"
#define Inf_color       "{8FC248}"

