//========= Copyright (c) 2017-2023 Darkside Interactive, Ltd. All rights reserved. ============//
//
// Цель: подключение SQL базы данных
//
//=============================================================================//


#define SQL_HOSTNAME  "127.0.0.1"
#define SQL_USERNAME "root"
#define SQL_DATABASE   "icbrk2"
#define SQL_PASSWORD  ""


// enter point of the db and used the synt db->mysql_close(...) for example;
new MySQL:db;