//========= Copyright (c) 2017-2023 Darkside Interactive, Ltd. All rights reserved. ============//
//
// Цель: макросы наименований: имя сервера в списке серверов, название карты, версия, ссылка на вк.
//
//=============================================================================//


#define name_proj "CRMP"
#define map_proj "Russia"
#define version "0.0.1.1"
#define mode_name ""name_proj" : "version""
