//!============>> Copyright (c) 2017-2023 Darkside Interactive, Ltd. All rights reserved. <<============//
//
//? Цель: локальное соединение с SQL
//
//!=====================================================================================================//

#define LOCAL_SQL_HOSTNAME       "127.0.0.1"
#define LOCAL_SQL_USERNAME       "root"
#define LOCAL_SQL_DATABASE       "icbrk2"
#define LOCAL_SQL_PASSWORD       ""


// enter point of the db and used the synt db->mysql_close(...) for example;
new MySQL:db;